services:
  frontend:
    image: fius/drinklistv4-frontend
    ports:
      - 3000:80
    restart: always
    volumes:
      - ./frontend/public/environment:/app/build/environment:ro

  api:
    image: fius/drinklistv4-backend
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./data/backend:/usr/src/app/instance/db
    environment:
      - DOMAIN=127.0.0.1:5000
      - COOKIE_EXPIRE_TIME=4368
      - DB_CONNECTION=sqlite:///db/database.db
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=unsafe
      - MOD_USERNAME=mod
      - MOD_PASSWORD=unsafe
      - USER_PASSWORD=unsafe
      - UNDO_TIMELIMIT=5
      - AUTO_HIDE_DAYS=210
      #- USE_ALIAS=true
      #- MAIL_SERVER=
      #- MAIL_EMAIL=
      #- MAIL_USERNAME=
      #- MAIL_PASSWORD=
      #- MAIL_POSTFIX=